# Spec to run when a kURL cluster is down and in-cluster specs can't be run
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: all-journald-logs
spec:
  hostCollectors:
    # Logs for CRI, Kubelet, Kernel
    - run:
        collectorName: "journalctl-containerd-all"
        command: "journalctl"
        args: ["-u", "containerd", "--no-pager", "-S", "-a"]
    - run:
        collectorName: "journalctl-kubelet-all"
        command: "journalctl"
        args: ["-u", "kubelet", "--no-pager", "-S", "-a"]
    - run:
        collectorName: "journalctl-docker-all"
        command: "journalctl"
        args: ["-u", "docker", "--no-pager", "-S", "-a"]
    - run:
        collectorName: "journalctl-dmesg-all"
        command: "journalctl"
        args: ["--dmesg", "--no-pager", "-S", "-a"]
